sudo: required
dist: trusty
language: node_js
node_js:
  - "4"
  - "6"
  - "7"
after_success:
   - npm run coveralls
install:
  - npm install
before_script:
   - ./scripts/start-server.sh
   - node test/app-fixture.js &
script: make
after_script:
   - ./scripts/stop-server.sh
   - kill -9 `cat pid.txt`
